import { StyleSheet } from 'react-native';

const opacity = 'rgba(0, 0, 0, .9)';

const styles = StyleSheet.create({
  scannerLayout: {
    flex: 1,
    // padding: '2%',
  },
  layout: {
    flex: 1,
    padding: '2%',
    paddingTop: '1%',
  },
  card: {
    flex: 1,
    width: '100%',
    backgroundColor: '#F9F9F9',
    paddingBottom: '3%',
  },
  mainView: {
    flex: 1,
    height: '100%',
  },
  centerCard: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    backgroundColor: '#fff',
    marginTop: 12,
  },
  scannerView: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  scannerContainer: {
    flex: 1,
    flexDirection: 'column',
  },
  layerTop: {
    flex: 1,
    backgroundColor: opacity,
    justifyContent: 'center',
    alignContent: 'center',
  },
  layerCenter: {
    flex: 1,
    flexDirection: 'row',
  },
  layerLeft: {
    flex: 1,
    backgroundColor: opacity,
  },
  focused: {
    flex: 5,
  },
  layerRight: {
    flex: 1,
    backgroundColor: opacity,
  },
  layerBottom: {
    flex: 1,
    backgroundColor: opacity,
  },
  planSelectionContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: '3%',
    borderRadius: 5,
    height: '100%',
    marginTop: '2%',
    borderColor: '#E4E9F2',
    borderWidth: 0.5,
    paddingBottom: '2%',
  },
  timeLineContainer: {
    marginTop: '4%',
    width: '100%',
  },
  timeLineRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: '2%',
    alignItems: 'center',
  },
  circle: {
    backgroundColor: '#AA8FFF',
    borderRadius: 100,
    width: 12,
    height: 12,
    margin: 2.5,
    opacity: 0.25,
  },
  circleActive: {
    backgroundColor: '#AA8FFF',
    borderRadius: 100,
    width: 12,
    height: 12,
    margin: 2.5,
  },
  circleIconContainer: {
    backgroundColor: '#AA8FFF',
    borderRadius: 100,
    width: 50,
    height: 50,
    opacity: 0.35,
    alignItems: 'center',
    justifyContent: 'center',
  },
  spotiiGuaranteesContainer: {
    flexDirection: 'column',
    marginTop: '4%',
    justifyContent: 'space-between',
  },
  spotiiGuarantee: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: '4%',
  },
  guaranteeText: {
    flexDirection: 'column',
    marginLeft: '4%',
  },
  cardSelection: {
    marginTop: '4%',
    marginBottom: '10%',
  },
  cardLogo: {
    maxWidth: 35,
    maxHeight: 35,
    resizeMode: 'contain',
    flex: 1,
  },
  paymentInactive: {
    borderWidth: 2,
    borderRadius: 10,
    borderColor: 'grey',
    marginTop: '1%',
  },
  paymentActive: {
    borderWidth: 2,
    borderRadius: 10,
    borderColor: '#411361',
    marginTop: '1%',
  },
  paymentDisplay: {
    borderWidth: 2,
    borderRadius: 10,
    borderColor: '#411361',
    marginTop: '1%',
    width: '90%',
  },
  backdrop: {
    backgroundColor: 'white',
  },
  addCardModal: {
    minWidth: '96%',
    minHeight: 600,
  },
  modal: {
    borderRadius: 25,
  },
  center: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonGroup: {
    borderRadius: 100,
    flexDirection: 'row',
    marginTop: '2%',
  },
  groupButton: {
    flex: 1,
    backgroundColor: 'white',
  },
  groupButtonSelected: {
    flex: 1,
  },
  hidden: {
    opacity: 0,
  },
  lottieView: {
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  lottieViewOrderFail: {
    width: '100%',
    height: '100%',
    marginBottom: -120,
  },
  displayName: {
    textAlign: 'center',
    fontSize: 22,
    marginTop: '3%',
    marginBottom: '2%',
    fontWeight: '700',
  },
  paymentComplete: {
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
  },
  lottieViewContainer: {
    height: 210,
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: '2%',
  },
  documentLottieViewContainer: {
    maxHeight: '45%',
    alignItems: 'center',
    alignSelf: 'center',
    paddingRight: '6%',
  },
  planTypeSelector: {
    marginBottom: '4%',
  },
  radioButtonText: {
    color: '#AA8FFF',
    fontSize: 15,
  },
  planTypeDesc: {
    marginTop: '4%',
  },
  BottomSubmitActions: {
    flexDirection: 'column',
    position: 'absolute',
    bottom: 20,
    width: '100%',
    marginTop: '6%',
    paddingHorizontal: '3%',
  },
  DeclinedHeader: {
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 22.5,
    marginBottom: '1%',
  },
  DeclinedDesc: {
    // marginVertical: '1%',
    textAlign: 'center',
    fontSize: 15,
    color: '#717171',
  },
  DeclinedDescAlt: {
    // marginVertical: '2%',
    textAlign: 'center',
    fontSize: 15,
    color: '#717171',
  },
  phoneNumber: {
    fontSize: 15,
    fontWeight: '400',
    color: '#AA8FFF',
  },
  svgContainer: {
    flex: 1,
    alignItems: 'center',
    maxHeight: '50%',
  },
  alignTextLeft: {
    textAlign: 'left',
  },
  alignTextRight: {
    textAlign: 'right',
  },
  subText: {
    color: '#717171',
  },
  subTextWhite: {
    color: '#FFFFFF',
  },
  scannerCameraMessageView: {
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
  },
  scannerCameraIdUploadView: {
    justifyContent: 'center',
    alignItems: 'center',
    height: '90%',
  },
  spotiiWideErrorContainer: {
    marginHorizontal: '5%',
  },
  scannerDisclaimerHeader: {
    textAlign: 'center',
  },
  scannerDisclaimer: {
    textAlign: 'center',
    marginTop: '4%',
  },
  idTextContainer: {
    color: '#717171',
    marginBottom: '15%',
  },
  idAssetContainer: {
    marginTop: '5%',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '15%',
  },
  gcApprovedTextCenter: {
    textAlign: 'center',
  },
  gcApprovedInfoText: {
    fontSize: 13,
  },
  gcApprovedBold: {
    fontWeight: '700',
  },
  gcApprovedMarginVert: {
    marginVertical: 10,
  },
  popOverContent: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'center',
    maxWidth: '95%',
    height: 'auto',
    marginVertical: '5%',
    fontSize: 15,
  },
  popOverContentTextEn: {
    flexWrap: 'wrap',
    textAlign: 'left',
    fontSize: 14,
    fontWeight: '400',
  },

  popOverContentTextAr: {
    flexWrap: 'wrap',
    textAlign: 'right',
    fontSize: 18,
  },

  nfcScanButton: {
    position: 'absolute',
    bottom: 10,
    marginTop: '20%',
    width: '100%',
    borderRadius: 100,
  },
  idUploadHeader: {
    textAlign: 'center',
    fontWeight: '400',
    fontSize: 28,
  },
  idUploadButton: {
    position: 'absolute',
    bottom: 10,
    width: '100%',
    borderRadius: 8,
    paddingVertical: 15,
  },
  flexColumn: {
    flexDirection: 'column',
  },
  flexRowReverse: {
    flexDirection: 'row-reverse',
  },
  flexRow: {
    flexDirection: 'row',
  },
  accordion: {
    width: '100%',
  },
  accordionSelectPlus: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  accordionSelectOuter: {
    width: 20,
    height: 20,
    borderRadius: 50,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
  },
  accordionSelectInner: {
    width: 12,
    height: 12,
    borderRadius: 50,
  },
  accordionHeaderContainer: {
    // flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    padding: 10,
    borderRadius: 5,
    marginTop: '3%',
    backgroundColor: '#F9F9F9',
  },
  accordionHeaderContainerSelected: {
    // flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingTop: 10,
    borderColor: '#AA8FFF',
    borderWidth: 1,
    borderBottomColor: '#FFFFFF',
    borderTopRightRadius: 5,
    borderTopLeftRadius: 5,
    marginTop: '3%',
  },
  headerContainerSelectedFullBorder: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    padding: 10,
    borderColor: '#AA8FFF',
    borderWidth: 1,
    borderRadius: 5,
    marginTop: '3%',
  },
  pmContainer: {
    paddingHorizontal: 5,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  accordionBody: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    borderColor: '#AA8FFF',
    borderWidth: 1,
    borderTopColor: '#FFFFFF',
    minHeight: 60,
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 20,
    borderBottomRightRadius: 5,
    borderBottomLeftRadius: 5,
    borderBottomWidth: 1,
  },
  paymentOptionListContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    // marginHorizontal: 3,
    paddingHorizontal: '3%',
    borderRadius: 5,
    height: '100%',
    marginTop: '2%',
    paddingBottom: '15%',
    borderColor: '#E4E9F2',
    borderWidth: 0.5,
  },
  addNewCardSpinner: {
    marginTop: '2%',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },
  backArrowContainer: {
    position: 'absolute',
    left: '1%',
    top: '30%',
    width: 30,
    height: 30,
  },
  accordionBodyNoPadding: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    borderColor: '#AA8FFF',
    borderWidth: 1,
    borderTopColor: '#FFFFFF',
    // height: 325,
    paddingTop: 0,
    paddingHorizontal: 0,
    paddingBottom: 0,
    borderBottomRightRadius: 5,
    borderBottomLeftRadius: 5,
    borderBottomWidth: 1,
  },
  accordionHeaderDivider: {
    width: '95%',
    borderWidth: 1,
    marginTop: 7,
    borderColor: '#CCCCCC',
    alignSelf: 'center',
  },
  processorLogoContainer: {
    flexDirection: 'row',
    marginHorizontal: 10,
    justifyContent: 'space-evenly',
    paddingHorizontal: '3%',
    flex: 1,
  },
  processorLogo: {
    maxWidth: 30,
    maxHeight: 30,
    resizeMode: 'contain',
    flex: 1,
  },
  tipsHeaderText: {
    color: '#1A0826',
    fontSize: 14,
    paddingHorizontal: 10,
  },
  tipsHeaderSubText: {
    color: '#717171',
    fontSize: 14,
    paddingHorizontal: 10,
  },
  tipsHeaderTextSinglePlan: {
    color: '#1A0826',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 17.5,
    marginTop: '3%',
  },
  tipsHeaderSubTextSinglePlan: {
    color: '#717171',
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 15,
  },
  paymentFormHeader: {
    paddingHorizontal: 2,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 14,
    paddingTop: 10,
    flexDirection: 'row',
    backgroundColor: 'white',
    borderWidth: 0.5,
    borderColor: '#E4E9F2',
    borderRadius: 4,
  },
  displayNameHeading: {
    textAlign: 'center',
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '400',
    color: '#1A0826',
  },
  displayNameSubHeading: {
    textAlign: 'center',
    fontSize: 14,
    lineHeight: 17.5,
    fontWeight: '400',
    color: '#353535',
    paddingTop: 2,
  },
});

export default styles;
