import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  slide: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#9DD6EB',
    // padding: 15,
  },
  text: {
    color: '#fff',
    fontSize: 30,
    fontWeight: 'bold',
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textBlock: {
    textAlign: 'center',
    alignItems: 'center',
    marginHorizontal: '5%',
    marginBottom: '2%',
  },
  subTextBlock: {
    textAlign: 'center',
    alignItems: 'center',
    marginHorizontal: '9%',
    fontSize: 18,
    marginBottom: '4%',
  },
  textBlockGray: {
    textAlign: 'center',
    alignItems: 'center',
    color: '#888',
    fontSize: 14,
  },
  fullScreen: {
    flex: 1,
    padding: '2%',
    backgroundColor: 'white',
    paddingTop: '10%',
  },
  iconRound: {
    width: 35,
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
    borderWidth: 1,
    borderColor: '#AA8FFF',
  },
  icon: {
    width: 60,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
    position: 'absolute',
    alignContent: 'center',
    top: '50%',
    left: 10,
    bottom: 0,
    marginTop: -15,
    backgroundColor: 'rgba(255,77,74,.1)',
  },
  image: {
    height: '60%',
    width: '100%',
    resizeMode: 'contain',
    borderRadius: 10,
    marginTop: 40,
    marginBottom: 0,
  },
  imageQr: {
    height: '50%',
    width: '100%',
    resizeMode: 'contain',
    borderRadius: 10,
    marginTop: '20%',
    marginBottom: 0,
  },
  imageComplete: {
    height: '50%',
    width: '100%',
    resizeMode: 'contain',
    borderRadius: 10,
    marginTop: 40,
    marginBottom: 0,
  },
  imageConfirm: {
    height: '60%',
    width: '100%',
    resizeMode: 'contain',
    borderRadius: 10,
    marginTop: 0,
    marginBottom: 10,
  },
  btnContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    position: 'absolute',
    bottom: 40,
    left: 0,
    right: 0,
  },
  circle: {
    backgroundColor: '#AA8FFF',
    borderRadius: 100,
    width: 12,
    height: 12,
    margin: 5,
    opacity: 0.35,
  },
  circleActive: {
    backgroundColor: '#AA8FFF',
    borderRadius: 100,
    width: 12,
    height: 12,
    margin: 5,
  },
  paymentControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  view: {
    justifyContent: 'flex-start',
    marginTop: 10,
  },
  cardView: {
    marginLeft: 60,
  },
  block: {
    borderWidth: 0,
    padding: 0,
    width: '100%',
    flexDirection: 'row',
  },
  textBlockWhite: {
    textAlign: 'left',
    alignItems: 'flex-start',
    color: '#888',
    fontSize: 18,
    marginBottom: '3%',

  },
  textBlockWhiteHeading: {
    textAlign: 'left',
    alignItems: 'flex-start',
    color: '#222',
    fontSize: 18,
    marginBottom: '3%',
  },
  step1Desc: {
    marginTop: '20%',
  },
  step2Desc: {
    marginTop: '10%',
  },
});

export default styles;
