import { StyleSheet } from 'react-native';
import Constants from 'expo-constants';

const styles = StyleSheet.create({
  form: {
    flex: 1,
    paddingTop: Constants.statusBarHeight,
    justifyContent: 'center',
  },
  layout: {
    flex: 1,
    paddingTop: Constants.statusBarHeight,
    justifyContent: 'center',
    backgroundColor: '#ffffff',
  },
  searchBarView: {
    justifyContent: 'center',
    position: 'absolute',
    paddingTop: 24,
  },
  merchantPageDetailView: {
    marginHorizontal: '5%',
    // maxHeight: '100%',
  },
  merchantCTA: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(26, 8, 38, 0.25)',
  },
  merchantPageButtonText: {
    fontSize: 20,
    color: '#ffffff',
  },
  merchantPageDesc: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 9,
  },
  affiliatePageDesc: {
    marginVertical: 9,
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 17.5,
    color: '#1A0826',
    width: '100%',
  },
  merchantPageCashbackInfo: {
    flexDirection: 'row',
    marginVertical: '1.5%',
  },
  cashbackSubheading: {
    color: '#1A0826',
    fontWeight: '300',
    fontSize: 14,
    lineHeight: 17.5,
  },
  merchantPageCategoryNames: {
    color: '#1A0826',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 17.5,
  },
  merchantPageCashbackPercent: {
    color: '#AA8FFF',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 17.5,
  },
  affiliatePageHeading: {
    fontWeight: '400',
    fontSize: 28,
    lineHeight: 35,
    color: '#1A0826',
    marginTop: 8,
  },
  affiliateDealsHeading: {
    fontWeight: '400',
    fontSize: 28,
    lineHeight: 35,
    color: '#190A0A',
    marginBottom: 5,
    marginTop: 15,
  },
  affiliateDealsBody: {
    marginTop: 5,
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 17.5,
    color: '#1A0826',
    marginBottom: 6,
  },
  affiliateDealsTerms: {
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 15,
    color: '#717171',
    marginBottom: 7,
  },
  affiliateCashbackHeading: {
    fontWeight: '400',
    fontSize: 28,
    lineHeight: 35,
    color: '#1A0826',
    marginBottom: 5,
  },
  affiliateCategoryHeading: {
    fontWeight: '500',
    fontSize: 18,
    lineHeight: 22.5,
    color: '#1A0826',
    marginBottom: 5,
  },
  installmentsHeading: {
    fontSize: 28,
    lineHeight: 35,
    fontWeight: '400',
    color: '#1A0826',
  },
  affiliatePageButtonText: {
    fontSize: 16,
    color: '#ffffff',
    lineHeight: 20,
    fontWeight: '600',
    textAlign: 'center',
  },
  merchantPageLink: {
    backgroundColor: '#411361',
    borderColor: '#411361',
    fontWeight: '700',
    marginHorizontal: 20,
    zIndex: 1000,
  },
  merchantPageButtonView: {
    position: 'absolute',
    bottom: 20,
    width: '100%',
    paddingTop: 10,
    backgroundColor: '#ffffff',
  },
  backdrop: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  topActionsRight: {
    position: 'absolute',
    top: 12,
    right: '6%',
  },
  header: {
    alignItems: 'center',
    marginBottom: '2%',
  },
  input: {
    marginHorizontal: '9%',
    marginVertical: 8,
  },
  middleContainer: {
    flexDirection: 'row',
  },
  middleInput: {
    width: 128,
  },
  signInButton: {
    marginHorizontal: '9%',
    borderRadius: 10,
    marginVertical: '4%',
  },
  cantSignInButton: {
    marginHorizontal: 20,
    borderRadius: 10,
    marginTop: '2%',
  },
  noAccountButton: {
    marginHorizontal: 13,
    borderRadius: 10,
    borderColor: 'white',
    backgroundColor: 'transparent',
    marginTop: '2%',
  },
  passwordInput: {
    textAlign: 'right',
    marginHorizontal: 12,
    marginVertical: 8,
  },
  text: {
    marginHorizontal: 5,
    textAlign: 'center',
    marginBottom: 18,
  },
  subText: {
    marginHorizontal: 12,
    textAlign: 'center',
    fontSize: 22,
    color: '#545454',
  },
  label: {
    marginBottom: '2%',
    fontSize: 20,
    fontWeight: 'normal',
    color: '#545454',
  },
  caption: {
    marginTop: '1%',
    fontSize: 18,
  },
  card: {
    marginTop: '2%',
  },
  block: {
    borderWidth: 0,
    padding: 0,
    paddingLeft: '1%',
    paddingRight: '1%',
    marginVertical: 5,
    flexDirection: 'row',
  },
  bgLogo: {
    resizeMode: 'cover',
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    paddingVertical: '10%',
    paddingHorizontal: '10%',
    borderRadius: 8,
  },
  backButtonMerchantPage: {
    backgroundColor: '#ffffff',
    borderRadius: 50,
    width: 40,
    height: 40,
    borderWidth: 1,
    borderColor: '#c2c4c6',
    alignContent: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: 10,
    left: 15,
  },
  heroBlock: {
    borderWidth: 0,
    padding: 0,
    height: 220,
    width: '100%',
    flexDirection: 'row',
  },
  merchantAppShopView: {
    borderWidth: 0,
    padding: 0,
    height: 400,
    width: '90%',
    marginTop: 18,
    marginHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  merchantAppShopImage: {
    resizeMode: 'contain',
    position: 'relative',
    borderWidth: 0,
    marginBottom: 10,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    flex: 1,
  },
  stepsToShopContainer: {
    backgroundColor: '#ede6ff',
    flexDirection: 'column',
    padding: 20,
    marginVertical: 6,
    width: '100%',
  },
  timelineStamp: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '25%',
    paddingHorizontal: 15,
  },
  timelinePie: {
    paddingHorizontal: 2,
    borderWidth: 1,
    width: 46,
    borderRadius: 30,
    height: 46,
    justifyContent: 'center',
  },
  timelineTextContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 15,
  },
  installmentText: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 17.5,
    color: '#717171',
  },
  TimelineDueText: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 17.5,
    color: '#1A0826',
  },
  offerContainer: {
    paddingHorizontal: 15,
    marginBottom: 100,
  },
  shopDirMerchantText: {
    width: '65%',
    height: 60,
    fontSize: 10,
    paddingVertical: 5,
    marginLeft: 10,
    marginRight: 10,
  },
  bgImage: {
    width: '100%',
    resizeMode: 'cover',
    borderRadius: 8,
    marginBottom: 10,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    // elevation: 5,
  },
  bgAffiliateImage: {
    width: '100%',
    resizeMode: 'cover',
    borderRadius: 8,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#c2c4c6',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  heroImage: {
    position: 'relative',
    borderWidth: 0,
    // marginBottom: 10,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    elevation: 5,
    flex: 1,
  },
  view: {
    justifyContent: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: '4%',
  },
  image: {
    resizeMode: 'contain',
    flex: 1,
  },
  heroLogo: {
    resizeMode: 'cover',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#c2c4c6',
    position: 'absolute',
    justifyContent: 'center',
    left: 20,
    bottom: 10,
    paddingVertical: '8%',
    paddingHorizontal: '12%',
    transform: [{ skewY: '-5deg' }],
  },
  heroLogoBorderNone: {
    resizeMode: 'cover',
    height: '50%',
    width: '23%',
    borderWidth: 1,
    borderColor: 'white',
    position: 'absolute',
    justifyContent: 'center',
    left: 20,
    bottom: 20,
    paddingVertical: '10%',
    paddingHorizontal: '10%',
    borderRadius: 50,
  },
  heroLogoIcon: {
    flex: 1,
    width: undefined,
    height: undefined,
    resizeMode: 'contain',
    transform: [{ skewY: '5deg' }],
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modal: {
    maxWidth: '98%',
    minWidth: '94%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginModalView: {
    justifyContent: 'center',
    padding: 15,
    borderRadius: 12,
    backgroundColor: 'white',
    width: '95%',
  },
  loginHeader: {
    justifyContent: 'space-between',
  },
  loginModaltext: {
    fontSize: 30,
    lineHeight: 43.75,
    fontWeight: '400',
    color: '#1A0826',
  },
  LoginCTA: {
    marginTop: 30,
    marginBottom: 15,
  },
  loginModalSubheading: {
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 26,
    color: '#717171',
  },
  cashbackHiwHeading: {
    fontWeight: '400',
    fontSize: 18,
    lineHeight: 22.5,
    color: '#1A0826',
  },
  cashbackHiwSubheading: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 22,
    color: '#717171',
  },
  modalView: {
    width: '90%',
  },
  modalTextButton: {
    color: '#AA8FFF',
    lineHeight: 30,
    fontSize: 16,
    borderBottomWidth: 1,
    paddingTop: 10,
    paddingBottom: 10,
    borderColor: '#eee',
  },
  actions: {
    flexDirection: 'row',
    marginTop: 20,
  },
  buttonEn: {
    marginRight: 10,
    height: 15,
  },
  buttonAr: {
    marginRight: 10,
    height: 15,
  },
  cancelBtn: {
    height: 15,
  },
  exploreMore: {
    textAlign: 'right',
    fontSize: 22,
    color: '#AA8FFF',
    marginRight: '9%',
    marginBottom: '2%',
  },
  sectionHeading: {
    width: '100%',
    marginTop: '5%',
    marginBottom: '2%',
    fontSize: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionHeadingSearchEn: {
    width: '100%',
    marginTop: '5%',
    marginBottom: '2%',
    fontSize: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginLeft: 16,
  },
  sectionHeadingSearchAr: {
    width: '100%',
    marginTop: '5%',
    marginBottom: '2%',
    fontSize: 20,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingRight: 16,
  },
  categoryDivider: {
    borderWidth: 1,
    borderColor: '#000000',
    opacity: 0.05,
    marginBottom: 20,
    marginTop: 0,
    width: '100%',
  },
  displayNameSingleCat: {
    fontSize: 17,
    paddingVertical: 10,
  },
  maxCashbackSingleCat: {
    color: '#aaaaaa',
    fontSize: 14,
  },
  displayNameAllCats: {
    fontSize: 12,
    lineHeight: 16,
    paddingVertical: 0,
    textAlign: 'center',
    textAlignVertical: 'center',
    height: 32,
  },
  maxCashbackAllCats: {
    color: '#FFFFFF',
    fontSize: 9,
    lineHeight: 12.5,
    textAlign: 'center',
    paddingVertical: 2,
    backgroundColor: '#AA8FFF',
    position: 'absolute',
    bottom: 42,
    left: 0,
    right: 0,
  },
  dealContainer: {
    position: 'absolute',
    left: 0,
    elevation: 5,
    backgroundColor: '#DCF995',
    borderTopLeftRadius: 8,
    // borderBottomRightRadius: 8,
  },
  merchantDealText: {
    color: '#1A0826',
    fontSize: 9,
    textAlign: 'center',
    paddingVertical: 2,
    paddingHorizontal: 7,
  },
  couponDealText: {
    fontSize: 9,
    fontWeight: '400',
    textAlign: 'center',
    paddingVertical: 2,
    paddingHorizontal: 2,
  },
  filterButton: {
    zIndex: 100,
    borderRadius: 45,
  },
  filterOverlay: {
    flex: 1,
    height: '100%',
    width: '100%',
    position: 'absolute',
    left: 0,
    top: 0,
    opacity: 1,
    zIndex: 2147483647,
    backgroundColor: 'black',
    paddingTop: Constants.statusBarHeight,
  },
  filterOptionsHorizontal: {
    color: 'white',
    fontSize: 19,
    marginHorizontal: 20,
    textAlignVertical: 'center',
  },
  filterOptions: {
    color: 'white',
    fontSize: 19,
    marginHorizontal: 20,
    textAlignVertical: 'center',
    paddingTop: '5%',
    paddingBottom: '5%',
  },
  filterOptionsSelected: {
    color: '#AA8FFF',
    fontWeight: '700',
    fontSize: 19,
    marginHorizontal: 20,
    textAlignVertical: 'center',
    paddingTop: '5%',
    paddingBottom: '5%',
  },
  filterHeadEnOptions: {
    color: 'white',
    fontWeight: '700',
    display: 'flex',
    textAlign: 'left',
    alignSelf: 'flex-start',
    fontSize: 22,
    borderBottomWidth: 1,
    borderBottomColor: '#ffffff',
    marginHorizontal: 10,
    textAlignVertical: 'center',
    paddingTop: '5%',
    paddingBottom: '5%',
    marginBottom: '5%',
  },
  filterHeadArOptions: {
    color: 'white',
    fontWeight: '700',
    display: 'flex',
    textAlign: 'right',
    alignSelf: 'flex-end',
    fontSize: 22,
    borderBottomWidth: 1,
    borderBottomColor: '#ffffff',
    marginHorizontal: 10,
    textAlignVertical: 'center',
    paddingTop: '5%',
    paddingBottom: '5%',
    marginBottom: '5%',
  },
  subFilterOptionsEn: {
    color: 'white',
    fontSize: 19,
    textAlign: 'left',
    marginHorizontal: 25,
    textAlignVertical: 'center',
    paddingTop: '5%',
    paddingBottom: '5%',
    borderLeftColor: '#ffffff',
    borderLeftWidth: 1,
  },
  subFilterFontStyle: {
    color: 'white',
    fontSize: 19,
  },
  subFilterFontStyleSelected: {
    color: '#AA8FFF',
    fontSize: 19,
    fontWeight: '700',
  },
  subFilterOptionsAr: {
    color: 'white',
    fontSize: 19,
    textAlign: 'right',
    marginHorizontal: 25,
    textAlignVertical: 'center',
    paddingTop: '5%',
    paddingBottom: '5%',
    borderRightColor: '#ffffff',
    borderRightWidth: 1,
  },
  shopTypeSelector: {
    color: 'white',
    fontSize: 19,
    marginHorizontal: 10,
    textAlignVertical: 'center',
  },
  shopTypeSelectorSelected: {
    color: '#AA8FFF',
    fontWeight: '700',
    fontSize: 19,
    marginHorizontal: 10,
    textAlignVertical: 'center',
  },
  spinnerContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    marginVertical: '50%',
  },
  noResultsText: {
    textAlign: 'center',
    marginVertical: 10,
    fontSize: 14,
    fontWeight: '700',
  },
  animationOpacity: {
    flexDirection: 'row',
    marginHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: '6%',
    zIndex: 1000,
  },
  scrollView: {
    flexGrow: 0,
    marginBottom: 75,
  },
  filterClose: {
    maxWidth: 60,
  },
  centerSpinnerContainer: {
    alignItems: 'center',
    width: '100%',
  },
  couponCodeCTA: {
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20,
    color: '#AA8FFF',
  },
  couponCode: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 17.5,
    color: '#353535',
  },
});

export default styles;
